/* Synthetic-only UI. Native WebAuthn, no third-party script or local token storage. */
(()=>{'use strict';const $=id=>document.getElementById(id);let documentId=null,mandateId=null;
const decode=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),x=>x.charCodeAt(0));
const encode=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function options(j){const o={...j,challenge:decode(j.challenge)};if(j.user)o.user={...j.user,id:decode(j.user.id)};for(const k of ['allowCredentials','excludeCredentials'])if(j[k])o[k]=j[k].map(c=>({...c,id:decode(c.id)}));return o;}
function credential(c){const r={id:c.id,rawId:encode(c.rawId),type:c.type,response:{},clientExtensionResults:c.getClientExtensionResults()};for(const key of ['clientDataJSON','attestationObject','authenticatorData','signature','userHandle'])if(c.response[key])r.response[key]=encode(c.response[key]);if(c.response.getTransports)r.response.transports=c.response.getTransports();return r;}
async function api(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,data:await r.json()};}
function checked(r){if(r.status!==200)throw Error(r.data.error||'REQUEST_REJECTED');return r.data;}
function text(host,value){host.replaceChildren();const p=document.createElement('pre');p.textContent=JSON.stringify(value,null,2);host.append(p);}
async function refresh(){const r=await api('/api/session');const ok=r.status===200;$('workspace').hidden=!ok;$('access').hidden=ok;if(ok){$('who').textContent=r.data.subject;text($('documents'),r.data.documents);text($('receipts'),r.data.receipts);text($('audit'),r.data.audit);documentId=r.data.documents.at(-1)?.id||null;mandateId=r.data.mandates.filter(x=>!x.revoked&&x.expires*1000>Date.now()).at(-1)?.id||null;}else{documentId=mandateId=null;for(const k of ['documents','scope','receipts','audit'])$(k).replaceChildren();}$('grant').disabled=!documentId;for(const k of ['prepare-one','prepare-two','submit','revoke'])$(k).disabled=!mandateId;return r;}
async function enroll(invite){const o=checked(await api('/api/register/options',{invite}));const c=await navigator.credentials.create({publicKey:options(o.options)});checked(await api('/api/register/verify',{ceremony_id:o.ceremony_id,credential:credential(c)}));$('invite').value='';return refresh();}
async function login(subject){const o=checked(await api('/api/login/options',{subject}));const c=await navigator.credentials.get({publicKey:options(o.options)});checked(await api('/api/login/verify',{ceremony_id:o.ceremony_id,credential:credential(c)}));return refresh();}
async function grant(did){const o=checked(await api('/api/mandates/options',{document:did,templates:['information','suivi']}));text($('scope'),o.scope);const c=await navigator.credentials.get({publicKey:options(o.options)});const r=checked(await api('/api/mandates/verify',{ceremony_id:o.ceremony_id,credential:credential(c)}));mandateId=r.id;await refresh();return r;}
function bind(id,fn){$(id).addEventListener('click',async()=>{const b=$(id);b.disabled=true;try{const r=await fn();$('status').textContent=typeof r==='string'?r:'Opération de test terminée ; aucune démarche réelle effectuée.';}catch(e){$('status').textContent='Opération refusée ou interrompue : '+e.message;}finally{await refresh();if(['login','enroll','logout','create-document','revoke-all'].includes(id))b.disabled=false;}});}
bind('enroll',()=>enroll($('invite').value));bind('login',()=>login($('subject').value));
bind('create-document',async()=>{const r=checked(await api('/api/documents',{}));documentId=r.id;return r;});bind('grant',()=>grant(documentId));
for(const [id,template]of [['prepare-one','information'],['prepare-two','suivi']])bind(id,async()=>{const r=checked(await api('/api/prepare',{mandate:mandateId,template}));text($('scope'),r);return r;});
bind('submit',async()=>{const r=checked(await api('/api/submit-fixture',{mandate:mandateId,template:'information'}));text($('scope'),r);return r;});
bind('revoke',async()=>{checked(await api('/api/revoke',{mandate:mandateId}));return 'Mandat révoqué ; la préparation et le dépôt futurs sont refusés.';});
bind('revoke-all',async()=>{checked(await api('/api/revoke-all',{}));return 'Clés, sessions et mandats de ce compte fictif révoqués.';});bind('logout',async()=>{checked(await api('/api/logout',{}));return 'Session de test déconnectée.';});
window.PilotUI=Object.freeze({api,enroll,login,grant,refresh,credential,options});refresh();})();
