[package]
name = "scic-ohttp-runtime"
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"
publish = false

[[bin]]
name = "scic_ohttp_runtime"
path = "src/main.rs"

[dependencies]
base64 = "=0.22.1"
ohttp = { version = "=0.8.0", default-features = false, features = ["client", "server", "rust-hpke"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
sha2 = "=0.10.9"
