const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const page=fs.readFileSync('docs/france-debt-rate-risk-live-2026-10-02.html','utf8');
const script=page.match(/<script>([\s\S]*?)<\/script>/)[1];
const j=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-live.json','utf8'));
const node=()=>({textContent:'',innerHTML:'',dataset:{},classList:{add(){},remove(){}},style:{setProperty(){}},querySelector(){return node()},setAttribute(){},addEventListener(){},animate(){}});
const nodes=new Map(),document={getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);},querySelectorAll(){return[]},body:node(),documentElement:node()};
const c=vm.createContext({document,window:{matchMedia(){return{matches:true}}},console,Date,Number,Math,String,Array,Object,JSON,setTimeout(){},Blob:class{},URL,ResizeObserver:class{},snapshot:j});
vm.runInContext(script.slice(0,script.lastIndexOf('\n// LA_BETE_BOOT_START')),c,{timeout:3000});
const evaluate=s=>vm.runInContext(s,c,{timeout:3000});
assert(evaluate('acceptCanonical(snapshot)'));
const headline=nodes.get('realityHeadline').textContent;
const older=structuredClone(j);older.sequence--;c.candidate=older;
assert.equal(evaluate('acceptCanonical(candidate)'),false);
assert.equal(nodes.get('realityHeadline').textContent,headline);
const bad=structuredClone(j);bad.policy.political_recommendation='AUTO';c.candidate=bad;
assert.equal(evaluate('acceptCanonical(candidate)'),false);
bad.policy.political_recommendation='NONE';bad.france_binding.territorial_imputation=true;
assert.equal(evaluate('acceptCanonical(candidate)'),false);
const fresh=structuredClone(j);fresh.sequence++;fresh.updated_at=new Date(Date.parse(j.updated_at)+1000).toISOString();c.candidate=fresh;
assert(evaluate('acceptCanonical(candidate)'));
const selfModel=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-evolution.json','utf8')).self_model;
c.selfModel=selfModel;evaluate('renderSelfModel(selfModel)');
assert.match(nodes.get('selfMemorySummary').textContent,new RegExp(String(selfModel.health_memory.total_cycles)+' cycles'));
assert.match(nodes.get('selfCarePlan').innerHTML,/plan proposé, pas une exécution/);
assert.match(nodes.get('selfLearningSummary').textContent,/objectifs atteints/);
assert.match(nodes.get('selfCareLearning').innerHTML,/Attendu dès le cycle/);
const unsafe=structuredClone(selfModel);const first=Object.values(unsafe.health_memory.issues)[0];first.label='<img src=x onerror=alert(1)>';
c.selfModel=unsafe;evaluate('renderSelfModel(selfModel)');
assert(!nodes.get('selfMemoryIssues').innerHTML.includes('<img'));
evaluate('renderSelfModel(null)');assert.equal(nodes.get('selfCarePlan').innerHTML,'');assert.equal(nodes.get('selfCareLearning').innerHTML,'');
c.selfModel=selfModel;evaluate('renderSelfModel(selfModel)');
async function test(){
 c.fetch=async()=>{throw Error('Network OFF')};await evaluate('load()');
 assert.match(nodes.get('feed').innerHTML,/SNAPSHOT CONSERVÉ/);
 assert.equal(nodes.get('realityHeadline').textContent,headline);
 c.fetch=async()=>({ok:true,json:async()=>older});await evaluate('load()');
 assert.match(nodes.get('feed').innerHTML,/SNAPSHOT CONSERVÉ/);
 c.fetch=async()=>({ok:true,json:async()=>fresh});await evaluate('load()');
 assert.match(nodes.get('feed').innerHTML,/ÉTAT/);
 c.fetch=async()=>({ok:false,json:async()=>({})});await evaluate('run()');
 assert.match(nodes.get('runner').innerHTML,/UNKNOWN/);
 assert.equal(nodes.get('realityHeadline').textContent,headline);
 const functions=['renderDecisionTwin','renderMarket','renderTimeMachine','renderSim','buildBrief','initBeast'];
 for(const f of functions)assert.equal(evaluate('typeof '+f),'function');
 assert.match(evaluate('buildBrief(state)'),/national ≠ territorial/);
 c.unchanged=fresh;c.renderCount=0;evaluate('const originalRender=render;render=j=>{renderCount++;originalRender(j)};');
 assert.equal(evaluate('acceptCanonical(unchanged)'),true);assert.equal(c.renderCount,0);
 evaluate('render=originalRender');
 const evolution=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-evolution.json','utf8'));
 const timers=new Map();let timerId=0;const urls=[];
 c.setTimeout=(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId;};
 c.clearTimeout=id=>timers.delete(id);
 c.document.hidden=false;
 c.AbortController=class{constructor(){this.signal={};}abort(){this.signal.aborted=true;this.signal.reject?.(Error('timeout'));}};
 c.fetch=async(url,options)=>{urls.push(url);assert(options.signal);return {ok:true,json:async()=>url.includes('evolution')?evolution:url.includes('api.github')?{workflow_runs:[{status:'completed',conclusion:'success',run_started_at:new Date().toISOString()}]}:fresh};};
 assert.equal(await evaluate('refreshPulse()'),true);
 assert.equal(evaluate('pulseDelay()'),10000);
 assert.equal(Array.from(timers.values()).at(-1).ms,10000);
 assert.equal(urls.filter(u=>u.includes('api.github')).length,1);
 assert(!urls.some(u=>u.includes('?t=')));
 c.document.hidden=true;await evaluate('refreshPulse()');
 assert.equal(evaluate('pulseDelay()'),120000);
 assert.equal(urls.filter(u=>u.includes('api.github')).length,1);
 c.document.hidden=false;c.fetch=async()=>{throw Error('offline')};
 assert.equal(await evaluate('refreshPulse()'),false);
 assert.equal(evaluate('pulseDelay()'),20000);
 await evaluate('refreshPulse()');assert.equal(evaluate('pulseDelay()'),40000);
 let release;const gate=new Promise(r=>{release=r;});let heldCalls=0;
 c.fetch=async url=>{heldCalls++;if(url.includes('live.json'))await gate;return{ok:true,json:async()=>url.includes('evolution')?evolution:fresh};};
 const pending=evaluate('refreshPulse()');
 assert.equal(await evaluate('refreshPulse()'),false);
 assert.equal(heldCalls,1);release();assert.equal(await pending,true);
 assert.equal(evaluate('pulseDelay()'),10000);
 c.fetch=async(url,options)=>new Promise((resolve,reject)=>{options.signal.reject=reject;});
 const hung=evaluate('pulseFetch(FEED,{cache:"no-cache"})');
 const deadline=Array.from(timers.values()).find(x=>x.ms===15000);assert(deadline);deadline.fn();
 await assert.rejects(hung,/timeout/);
 let bodyReady;const bodyStarted=new Promise(resolve=>{bodyReady=resolve;});
 c.fetch=async(url,options)=>({ok:true,json:async()=>new Promise((resolve,reject)=>{options.signal.reject=reject;bodyReady();})});
 const bodyHung=evaluate('pulseFetch(FEED,{cache:"no-cache"})');await bodyStarted;
 const bodyDeadline=Array.from(timers.values()).find(x=>x.ms===15000);assert(bodyDeadline);bodyDeadline.fn();
 await assert.rejects(bodyHung,/timeout/);
 const wrong=structuredClone(evolution);wrong.source_snapshot_id='OJO-WRONG';
 c.fetch=async()=>({ok:true,json:async()=>wrong});assert.equal(await evaluate('loadEvolution()'),false);
 console.log('HYDRATION_AND_FAST_PULSE_VISIBLE_HIDDEN_BACKOFF_NO_OVERLAP_TIMEOUT_CANON_BINDING_PASS');
}
const watchdog=setTimeout(()=>{console.error("Hydration test did not complete");process.exit(1)},5000);
test().then(()=>clearTimeout(watchdog)).catch(e=>{console.error(e);process.exit(1)});
