#!/usr/bin/env node
/* End-to-end local TLS + actual WebAuthn verification with Chrome virtual keys.
   Synthetic subjects only. No citizen upload, external submission or native app change. */
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),https=require('node:https'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'),OUT=process.env.OJO_PRIVATE_PROOF_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'ojo-private-proof-'));
fs.mkdirSync(OUT,{recursive:true,mode:0o700});const state=fs.mkdtempSync(path.join(OUT,'synthetic-state-'));
let server,chrome,socket;const checks=[],exceptions=[],requests=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function main(){
 const python=process.env.OJO_PILOT_PYTHON;if(!python)throw Error('SET_OJO_PILOT_PYTHON_TO_ISOLATED_ENV');
 server=spawn(python,['app/server.py','--citizen-fixture-root',state],{cwd:ROOT,env:{...process.env,OJO_CITIZEN_SYNTHETIC_ONLY:'1'},stdio:['ignore','pipe','pipe']});
 let errors='';server.stderr.on('data',x=>errors=(errors+x).slice(-5000));
 for(let i=0;i<80&&!fs.existsSync(path.join(state,'fixture-server.json'));i++)await sleep(100);
 if(!fs.existsSync(path.join(state,'fixture-server.json')))throw Error('SERVER_START_FAILED '+errors);
 const info=JSON.parse(fs.readFileSync(path.join(state,'fixture-server.json'),'utf8')),origin=info.origin;
 const invitations=JSON.parse(fs.readFileSync(path.join(state,'test-invitations.json'),'utf8'));
 const cert=fs.readFileSync(path.join(state,'tls/certificate.pem'));
 function rawRequest(route,method='GET',body=null,headers={}){return new Promise((resolve,reject)=>{const u=new URL(route,origin);const r=https.request(u,{method,ca:cert,rejectUnauthorized:true,servername:'localhost',headers:{Host:u.host,...(body?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(JSON.stringify(body))}:{}),...headers}},res=>{let data='';res.on('data',b=>data+=b);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,data}));});r.on('error',reject);if(body)r.write(JSON.stringify(body));r.end();});}
 const profile=fs.mkdtempSync(path.join(OUT,'chrome-'));
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-port=0','--user-data-dir='+profile,'--ignore-certificate-errors-spki-list='+info.tls_spki_sha256_b64,'about:blank'],{stdio:['ignore','ignore','pipe']});
 chrome.stderr.on('data',()=>{});for(let i=0;i<80&&!fs.existsSync(path.join(profile,'DevToolsActivePort'));i++)await sleep(100);
 const port=Number(fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0]);
 const target=await(await fetch('http://127.0.0.1:'+port+'/json/new?about:blank',{method:'PUT'})).json();socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});
 let seq=0;const pending=new Map();socket.onmessage=e=>{const x=JSON.parse(e.data);if(x.id){const p=pending.get(x.id);if(p){pending.delete(x.id);x.error?p.reject(Error(JSON.stringify(x.error))):p.resolve(x.result);}}else if(x.method==='Runtime.exceptionThrown')exceptions.push(x.params.exceptionDetails.text);else if(x.method==='Network.requestWillBeSent')requests.push(x.params.request.url);};
 function send(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});}
 async function evaluate(expression){const r=await send('Runtime.evaluate',{expression:expression.includes('await ')?'(async()=>{'+expression+';return true;})()':expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value;}
 async function wait(expression,label){for(let i=0;i<80;i++){if(await evaluate(expression))return;await sleep(100);}throw Error('TIMEOUT '+label);}
 async function api(route,body){return evaluate('window.PilotUI.api('+JSON.stringify(route)+(body===undefined?'':','+JSON.stringify(body))+')');}
 function pass(name){checks.push(name);console.log('PASS '+name);}
 async function screenshot(name){const x=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(OUT,name+'.png'),Buffer.from(x.data,'base64'));}
 async function getCookies(){return (await send('Network.getCookies',{urls:[origin]})).cookies;}
 async function restoreCookies(cookies){await send('Network.clearBrowserCookies');for(const c of cookies)await send('Network.setCookie',{name:c.name,value:c.value,url:origin,secure:true,httpOnly:true,sameSite:'Strict',path:'/'});}
 await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('WebAuthn.enable',{enableUI:false});
 const auth=await send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'usb',ctap2Version:'ctap2_1',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 await send('Emulation.setDeviceMetricsOverride',{width:1200,height:950,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:origin});await send('Page.bringToFront');await wait('!!window.PilotUI','pilot initialized');
 assert.equal((await api('/api/session')).status,401);pass('private dossier unavailable without server-validated authentication');
 const noOrigin=await rawRequest('/api/documents','POST',{});assert.equal(noOrigin.status,403);const wrongOrigin=await rawRequest('/api/documents','POST',{}, {Origin:'https://untrusted.invalid'});assert.equal(wrongOrigin.status,403);pass('missing or mismatched Origin cannot invoke state-changing routes');
 const wrongHost=await rawRequest('/','GET',null,{Host:'untrusted.invalid'});assert.equal(wrongHost.status,403);pass('exact Host guard prevents rebinding to an unapproved origin');
 const publicRoot=await rawRequest('/');assert.match(publicRoot.headers['cache-control'],/no-store/);assert.match(publicRoot.headers['content-security-policy'],/frame-ancestors 'none'/);assert.equal(publicRoot.headers['access-control-allow-origin'],undefined);pass('private responses are no-store, no cross-origin wildcard and non-frameable');
 await evaluate('window.PilotUI.enroll('+JSON.stringify(invitations['test-citizen-a'])+')');const a=(await api('/api/session')).data;assert.equal(a.subject,'test-citizen-a');assert.equal(a.identity_verified,false);pass('first synthetic user enrolled by verified resident WebAuthn credential');
 const cookiesA=await getCookies(),sessionA=cookiesA.find(x=>x.name==='__Host-ojo_pilot_session');assert.ok(sessionA?.secure&&sessionA?.httpOnly&&sessionA.sameSite==='Strict');assert.ok(!(await evaluate('document.cookie')).includes('__Host-ojo_pilot_session'));pass('session cookie is Secure HttpOnly SameSite Strict and absent from script-readable cookies');
 const docA=(await api('/api/documents',{})).data;assert.ok(docA.id);const m=await evaluate('window.PilotUI.grant('+JSON.stringify(docA.id)+')');assert.ok(m.id);assert.equal(m.scope.actions[1],'SUBMIT_TO_LOCAL_FIXTURE_ONLY');pass('separate WebAuthn approval binds document hash and ten-minute limited mandate');
 const prep1=await api('/api/prepare',{mandate:m.id,template:'information'}),prep2=await api('/api/prepare',{mandate:m.id,template:'suivi'});assert.equal(prep1.status,200);assert.equal(prep2.status,200);assert.equal(prep1.data.document_digest,prep2.data.document_digest);assert.equal(prep1.data.body,prep2.data.body);pass('two requests reuse one approved document with no repeated enrolment');
 const first=await api('/api/submit-fixture',{mandate:m.id,template:'information'});assert.equal(first.status,200);assert.equal(first.data.real_external_action,false);assert.equal(first.data.provider_receipt.provider,'LOCAL_SYNTHETIC_RECEIVER');pass('bounded fixture submission returns an explicit non-administrative receipt');
 const again=await api('/api/submit-fixture',{mandate:m.id,template:'information'});assert.equal(again.data.state,'RECONCILIATION_REQUIRED');assert.equal((await api('/api/session')).data.receipts.length,1);pass('dispatch_once and durable claim prevent a duplicate fixture submission');
 const badFields=await api('/api/documents',{uploaded_file:'test-only payload must be refused'});assert.equal(badFields.status,400);const badScope=await api('/api/mandates/options',{document:docA.id,templates:['sign']});assert.equal(badScope.status,403);pass('uploads, private free-form records and signature authority are not accepted by pilot routes');
 await evaluate('window.PilotUI.refresh()');await screenshot('private-pilot-desktop');
 await send('Network.clearBrowserCookies');await evaluate('window.PilotUI.enroll('+JSON.stringify(invitations['test-citizen-b'])+')');assert.equal((await api('/api/session')).data.subject,'test-citizen-b');const docB=(await api('/api/documents',{})).data;const cookiesB=await getCookies();pass('second synthetic user has an independent verified credential and session');
 assert.equal((await api('/api/documents/'+docA.id)).status,404);assert.equal((await api('/api/prepare',{mandate:m.id,template:'suivi'})).status,404);assert.equal((await api('/api/revoke',{mandate:m.id})).status,404);const bo=(await api('/api/session')).data;assert.equal(bo.receipts.length,0);assert.ok(bo.documents.every(d=>d.id!==docA.id));pass('cross-citizen document, preparation, revocation, export-view and receipt access denied');
 await send('Network.clearBrowserCookies');const reconnect=await evaluate("window.PilotUI.login('test-citizen-a')");assert.equal(reconnect.status,200);pass('existing passkey reconnects without registration or document resubmission');
 await evaluate("window.__loginOptions=(await PilotUI.api('/api/login/options',{subject:'test-citizen-a'})).data;window.__assertion=PilotUI.credential(await navigator.credentials.get({publicKey:PilotUI.options(window.__loginOptions.options)}))");
 const verify=await evaluate("PilotUI.api('/api/login/verify',{ceremony_id:window.__loginOptions.ceremony_id,credential:window.__assertion})");assert.equal(verify.status,200);const replay=await evaluate("PilotUI.api('/api/login/verify',{ceremony_id:window.__loginOptions.ceremony_id,credential:window.__assertion})");assert.equal(replay.status,403);pass('actual signed assertion replay rejected after challenge consumption');
 await evaluate("window.__loginOptions=(await PilotUI.api('/api/login/options',{subject:'test-citizen-a'})).data;window.__badAssertion=PilotUI.credential(await navigator.credentials.get({publicKey:PilotUI.options(window.__loginOptions.options)}));window.__badAssertion.response.signature=window.__badAssertion.response.signature.slice(0,-3)+'AAA'");
 const bad=await evaluate("PilotUI.api('/api/login/verify',{ceremony_id:window.__loginOptions.ceremony_id,credential:window.__badAssertion})");assert.equal(bad.status,403);pass('tampered signed assertion rejected by maintained WebAuthn verifier');
 await send('WebAuthn.setUserVerified',{authenticatorId:auth.authenticatorId,isUserVerified:false});
 await evaluate("window.__loginOptions=(await PilotUI.api('/api/login/options',{subject:'test-citizen-a'})).data;window.__uvOpts=PilotUI.options(window.__loginOptions.options);window.__uvOpts.userVerification='discouraged';window.__noUV=PilotUI.credential(await navigator.credentials.get({publicKey:window.__uvOpts}))");
 const noUV=await evaluate("PilotUI.api('/api/login/verify',{ceremony_id:window.__loginOptions.ceremony_id,credential:window.__noUV})");assert.equal(noUV.status,403);await send('WebAuthn.setUserVerified',{authenticatorId:auth.authenticatorId,isUserVerified:true});pass('server rejects valid authenticator possession without required user verification');
 assert.equal((await api('/api/revoke',{mandate:m.id})).status,200);assert.equal((await api('/api/prepare',{mandate:m.id,template:'suivi'})).status,403);assert.equal((await api('/api/submit-fixture',{mandate:m.id,template:'suivi'})).status,403);pass('mandate revocation blocks both preparation and subsequent fixture submission');
 const m2=await evaluate('PilotUI.grant('+JSON.stringify(docA.id)+')');assert.equal((await api('/api/documents/replace-fixture',{document:docA.id})).status,200);assert.equal((await api('/api/prepare',{mandate:m2.id,template:'information'})).status,409);pass('document change invalidates previous approval instead of silently reusing it');
 await evaluate('PilotUI.refresh()');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await evaluate('window.scrollTo(0,0)');const width=await evaluate('({viewport:innerWidth,document:document.documentElement.scrollWidth})');assert.ok(width.document<=width.viewport+2);await screenshot('private-pilot-mobile');pass('private test interface fits 390px viewport without horizontal overflow');
 const lastA=await getCookies();assert.equal((await api('/api/revoke-all',{})).status,200);await restoreCookies(lastA);assert.equal((await api('/api/session')).status,401);assert.equal((await api('/api/login/options',{subject:'test-citizen-a'})).status,403);assert.equal((await api('/api/recover',{subject:'test-citizen-a'})).status,404);pass('all-access revocation invalidates old sessions and credentials, no fake recovery bypass');
 await restoreCookies(cookiesB);assert.equal((await api('/api/documents/'+docB.id)).status,200);assert.equal((await api('/api/session')).data.subject,'test-citizen-b');pass('revoking A does not revoke or leak B');
 const logout=await api('/api/logout',{});assert.equal(logout.status,200);await restoreCookies(cookiesB);assert.equal((await api('/api/session')).status,401);pass('logout revokes server state even if a stale cookie is restored');
 assert.ok(requests.every(u=>u.startsWith(origin)||u==='about:blank'));pass('private page sends no request to a third-party service');assert.equal(exceptions.length,0);pass('zero unhandled browser exceptions');
 const receipt={schema:'OJO_CITIZEN_PRIVATE_SYNTHETIC_BROWSER_PROOF_V1',status:'PASS',tested_at:new Date().toISOString(),checks,auth:'REAL_WEBAUTHN_SIGNATURE_VERIFICATION_WITH_CHROME_VIRTUAL_AUTHENTICATOR',tls:'LOCAL_SELF_SIGNED_TEST_CERTIFICATE_PINNED_FOR_TEST_BROWSER',publicly_trusted_tls:false,subjects:2,real_citizen_data_used:false,real_administrative_submissions:0,production_private_service:false,physical_iphone:false,independent_audit:false,desktop:[1200,950],mobile_emulation:[390,844],cookie_flags:{secure:true,httpOnly:true,sameSite:'Strict'},private_state_published:false};
 fs.writeFileSync(path.join(OUT,'private-browser-receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log('PRIVATE_BROWSER_PASS '+checks.length+' | '+path.join(OUT,'private-browser-receipt.json'));
}
main().catch(e=>{fs.writeFileSync(path.join(OUT,'failure.json'),JSON.stringify({error:e.stack,checks,exceptions},null,2));console.error(e.stack);process.exitCode=1;}).finally(()=>{if(socket)socket.close();if(chrome)chrome.kill('SIGTERM');if(server)server.kill('SIGTERM');});
