'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {start,sleep}=require('./avatar_browser_harness.cjs');
const root=path.resolve(__dirname,'..'),proof=path.join(root,'PROOF/LA_BETE_M03_CONTINUITY_20261005');
const output=path.join(proof,'browser-'+Date.now()),downloads=path.join(output,'downloads');fs.mkdirSync(downloads,{recursive:true});
const rows=[],requests=[];let h;const result=(name,detail={})=>{rows.push({name,result:'PASS',...detail});console.log('PASS',name);};
async function launch(){
 h=await start({root:path.join(root,'docs')});h.events['Page.javascriptDialogOpening']=()=>h.send('Page.handleJavaScriptDialog',{accept:true}).catch(()=>{});
 h.events['Network.requestWillBeSent']=p=>requests.push({url:p.request.url,method:p.request.method,post:p.request.postData||''});
 await h.send('Network.setBlockedURLs',{urls:['https://*']});await h.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
 await h.send('Page.navigate',{url:h.base+'/france-debt-rate-risk-live-2026-10-02.html?housegame=nicolas-avatar-v4&house=20261005-m03-draft#house-desk'});
 await h.wait("document.readyState==='complete'&&!!window.LaBeteParticipation?.draftState&&!!window.LaBeteAdvisoryHouseV5",'draft initialization');
}
async function click(sel,enter=false){
 await h.evaluate(`document.querySelector(${JSON.stringify(sel)}).scrollIntoView({block:'center',inline:'nearest',behavior:'instant'})`);await sleep(160);
 const p=await h.evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(sel)}),r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,t=document.elementFromPoint(x,y);return{x,y,hit:e===t||e.contains(t),hidden:r.width===0||r.height===0}})()`);
 assert.ok(p.hit&&!p.hidden,'Unreachable '+sel+' '+JSON.stringify(p));
 if(enter){await h.evaluate(`document.querySelector(${JSON.stringify(sel)}).focus()`);await h.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,text:'\r',unmodifiedText:'\r'});await h.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});}
 else{await h.send('Input.dispatchMouseEvent',{type:'mousePressed',x:p.x,y:p.y,button:'left',clickCount:1});await h.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:p.x,y:p.y,button:'left',clickCount:1});}
 await sleep(100);
}
async function desk(){await h.evaluate("LaBeteAdvisoryHouseV5.setRoom('desk')");await sleep(120);}
async function ask(q,enter=false){await desk();await h.evaluate("document.getElementById('beastDialogueInput').focus()");await h.send('Input.insertText',{text:q});await click('#beastDialogueSubmit',enter);await sleep(100);return h.evaluate('LaBeteParticipation.draftState()');}
async function openPanel(){await desk();if(!await h.evaluate("document.getElementById('beastDraftPanel').open"))await click('#beastDraftPanel summary');}
async function consent(){await openPanel();if(!await h.evaluate("document.getElementById('beastDraftScopeConsent').checked"))await click('#beastDraftScopeConsent');}
async function exportFile(){await consent();const prev=new Map(fs.readdirSync(downloads).map(x=>[x,fs.statSync(path.join(downloads,x)).mtimeMs]));await click('#beastExportDialogue');for(let i=0;i<80;i++){const f=fs.readdirSync(downloads).find(x=>x.endsWith('.json')&&(!prev.has(x)||fs.statSync(path.join(downloads,x)).mtimeMs!==prev.get(x)));if(f)return path.join(downloads,f);await sleep(100);}throw Error('No downloaded export: '+await h.evaluate("document.getElementById('beastDialogueNotice').textContent"));}
async function importFile(file){await consent();const doc=await h.send('DOM.getDocument');const n=await h.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'#beastDraftFile'});await h.send('DOM.setFileInputFiles',{nodeId:n.nodeId,files:[file]});await sleep(250);}
(async()=>{
 await launch();assert.equal(await h.evaluate('LaBeteParticipation.draftState()'),null);result('No invented dossier on startup');
 assert.equal(await h.evaluate("document.querySelectorAll('#beastDialogueForm').length"),1);result('Single existing form preserved');
 const qa='Quel est le TEC10 de la France ?',qb='Ma trésorerie de transport est tendue';
 const a=await ask(qa);assert.ok(a?.meta?.id);assert.equal(a.last_status,'CANONICAL_CONTEXT');result('Public question creates versioned draft A',a);
 await openPanel();await click('#beastExportDialogue');assert.match(await h.evaluate("document.getElementById('beastDialogueNotice').textContent"),/confirmez/);assert.equal(fs.readdirSync(downloads).length,0);result('Export requires scope confirmation');
 const afile=await exportFile(),apack=JSON.parse(fs.readFileSync(afile));assert.equal(apack.payload.meta.id,a.meta.id);assert.equal(apack.payload.conversation.length,1);result('Real browser download A retains references and identity',{file:afile});
 await click('#beastNewDraft');assert.equal(await h.evaluate('LaBeteParticipation.draftState()'),null);assert.equal(await h.evaluate("document.querySelectorAll('#beastDialogueLog .beastMessage').length"),0);result('New draft explicitly separates prior history');
 const b=await ask(qb,true);assert.notEqual(b.meta.id,a.meta.id);assert.equal(b.last_status,'OUT_OF_SCOPE');assert.equal(await h.evaluate('LaBeteAdvisoryHouseV5.state().room'),'desk');result('Draft B at keyboard remains unanalysed business context',b);
 await openPanel();for(const[k,v]of Object.entries({expected_outcome:'Mesurer un creux de trésorerie synthétique',horizon:'180 jours',constraints:'Données synthétiques uniquement'}))await h.evaluate(`(()=>{const e=document.getElementById(${JSON.stringify('beastDraft-'+k)});e.value=${JSON.stringify(v)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 const complete=await h.evaluate('LaBeteParticipation.draftState()');assert.equal(complete.qualification.code,'QUALIFIED_DRAFT');assert.equal(complete.qualification.native,'NOT_ADMITTED');result('Qualification reflects declared fields without native admission');
 const bfile=await exportFile(),bpack=JSON.parse(fs.readFileSync(bfile));assert.equal(bpack.payload.native_case_id,null);assert.equal(bpack.payload.native_mission_id,null);assert.equal(bpack.payload.conversation[0].result.references.length,0);result('Business export carries no national result or native authority',{file:bfile});
 await h.close();h=null;await launch();assert.equal(await h.evaluate('LaBeteParticipation.draftState()'),null);result('Actual browser process closure/reopen has no hidden persistence');
 await importFile(afile);await h.wait('!!LaBeteParticipation.draftState()?.restored','A import');assert.equal((await h.evaluate('LaBeteParticipation.draftState()')).meta.id,a.meta.id);assert.match(await h.evaluate("document.getElementById('beastDialogueLog').textContent"),/ARCHIVE IMPORTÉE · NON REVÉRIFIÉE/);assert.equal(await h.evaluate("document.getElementById('beastShareIdea').disabled"),true);result('A restored by file, labelled archive, not auto-shared');
 const afile2=await exportFile();assert.equal(JSON.parse(fs.readFileSync(afile2)).sha256,apack.sha256);result('A re-export after process restart is content-identical');
 await importFile(bfile);await h.wait(`LaBeteParticipation.draftState()?.meta.id===${JSON.stringify(b.meta.id)}`,'B import');assert.equal((await h.evaluate('LaBeteParticipation.draftState()')).meta.version,complete.meta.version);const log=await h.evaluate("document.getElementById('beastDialogueLog').textContent");assert.ok(log.includes(qb)&&!log.includes(qa));result('B restoration replaces A without mixing identity history or versions');
 const stateBefore=JSON.stringify(await h.evaluate('LaBeteParticipation.draftState()'));const corrupt=JSON.parse(fs.readFileSync(bfile));corrupt.payload.meta.horizon='999 jours';const bad=path.join(output,'altered.json');fs.writeFileSync(bad,JSON.stringify(corrupt));await importFile(bad);assert.match(await h.evaluate("document.getElementById('beastDialogueNotice').textContent"),/CHECKSUM_MISMATCH/);assert.equal(JSON.stringify(await h.evaluate('LaBeteParticipation.draftState()')),stateBefore);result('Altered file rejected without changing active B');
 const forged=JSON.parse(fs.readFileSync(bfile));forged.payload.native_mission_id='forged';const bad2=path.join(output,'forged.json');fs.writeFileSync(bad2,JSON.stringify(forged));await importFile(bad2);assert.match(await h.evaluate("document.getElementById('beastDialogueNotice').textContent"),/AUTHORITY/);assert.equal(JSON.stringify(await h.evaluate('LaBeteParticipation.draftState()')),stateBefore);result('Forged mission authorization rejected');
 for(const [w,ht]of [[1280,720],[390,844],[390,520]]){await h.send('Emulation.setDeviceMetricsOverride',{width:w,height:ht,deviceScaleFactor:1,mobile:w<500});await desk();await h.evaluate("document.getElementById('beastDraftPanel').open=false");await click('#beastDialogueSubmit',true);assert.equal(await h.evaluate("document.querySelectorAll('#beastDialogueForm').length"),1);await h.shot(path.join(output,'draft-'+w+'x'+ht+'.png'));result('Single form and submit reachable '+w+'x'+ht);}
 await desk();await h.evaluate("document.getElementById('beastDialogueInput').value='person@example.com'");await click('#beastDialogueSubmit');assert.equal(JSON.stringify(await h.evaluate('LaBeteParticipation.draftState()')),stateBefore);assert.ok(!await h.evaluate("document.getElementById('beastDialogueLog').textContent.includes('person@example.com')"));result('Sensitive input not retained in active draft or transcript');
 assert.equal(await h.evaluate("document.querySelector('.housePrivateDoor').getAttribute('href')"),'supra://private-office');assert.deepEqual(await h.evaluate('({local:localStorage.length,session:sessionStorage.length})'),{local:0,session:0});result('Payload-free private door and no persistent browser storage');
 assert.ok(!requests.some(r=>[qa,qb,'person@example.com'].some(q=>(decodeURIComponent(r.url)+r.post).includes(q))));result('No request carried entered draft text');
 await importFile(bfile);await h.wait('!!LaBeteParticipation.draftState()?.restored','final clean review');
 for(const [w,ht]of [[1280,900],[390,844]]){await h.send('Emulation.setDeviceMetricsOverride',{width:w,height:ht,deviceScaleFactor:1,mobile:w<500});await desk();await openPanel();await h.evaluate("document.getElementById('beastDraftPanel').scrollIntoView({block:'start',behavior:'instant'})");await sleep(150);await h.shot(path.join(output,'review-draft-'+w+'x'+ht+'.png'));}
 assert.equal(h.exceptions.length,0);result('No browser JavaScript exception');
 fs.writeFileSync(path.join(proof,'BROWSER_TESTS.json'),JSON.stringify({schema:'LA_BETE_M03_BROWSER_RECEIPT_V1',at:new Date().toISOString(),passed:rows.length,results:rows,output,external_requests_blocked:true,physical_mobile_tested:false,full_3d_navigation_tested:false},null,2));console.log('OUTPUT',output);
})().catch(async e=>{let diagnostic=null;try{diagnostic=await h?.evaluate("({notice:document.getElementById('beastDialogueNotice')?.textContent,input:document.getElementById('beastDialogueInput')?.value,focus:document.activeElement?.id,state:LaBeteParticipation.draftState()})");if(h)await h.shot(path.join(output,'failure.png'));}catch(_){}fs.writeFileSync(path.join(output,'FAILURE.json'),JSON.stringify({error:String(e),stack:e.stack,passed:rows,diagnostic,exceptions:h?.exceptions},null,2));console.error(e,diagnostic);process.exitCode=1;}).finally(async()=>{if(h)await h.close();});
