'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const D=require('../docs/assets/la-bete-dialogue.js'),O=require('../docs/assets/la-bete-observability.js');
const live=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-live.json')),evo=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-evolution.json'));
const before=JSON.stringify({live,evo});let n=0;const results=[];
function test(name,f){f();results.push({name,result:'PASS'});n++;}
for(const q of ['Je veux comprendre comment financer une nouvelle machine pour mon entreprise.','Quel taux pour mon crédit ?','Ma banque financera-t-elle cette acquisition ?','Ma trésorerie de transport est tendue','Que prouvent ces taux pour mon entreprise ?'])test('Hors périmètre : '+q,()=>{const a=D.analyze(q,{live,evolution:evo});assert.equal(a.status,'OUT_OF_SCOPE');assert.equal(a.references.length,0);assert.doesNotMatch(a.retained.join(' '),/4[,.]899|TEC10/);assert.equal(a.external_action,'NONE');});
test('Question TEC10 conserve les sources nationales',()=>{const a=D.analyze('Quel est le TEC10 de la France ?',{live,evolution:evo});assert.equal(a.status,'CANONICAL_CONTEXT');assert.ok(a.references.length>0);});
test('Objet territorial garde sa propre portée',()=>{const a=D.analyze('Que sais-tu de cette commune ?',{live,evolution:evo,object:{id:'fixture:commune',label:'Commune synthétique',kind:'COMMUNE',snapshot_id:live.snapshot_id,facts:[['Nom','Commune synthétique']],references:[]}});assert.equal(a.status,'OBJECT_CONTEXT');assert.doesNotMatch(a.retained.join(' '),/TEC/);});
test('Les quatre sources AFT ont une stratégie et un résultat explicites',()=>{const rows=O.sourceRows(live,evo).filter(s=>s.id.startsWith('AFT_')&&s.health==='UNAVAILABLE');assert.equal(rows.length,4);for(const row of rows){assert.equal(row.last_success,null);assert.equal(row.state,'ESCALATION_REQUIRED');assert.ok(row.last_attempt>row.cause_recorded_at);assert.ok(row.consequence&&row.next_strategy&&row.escalation_condition);assert.equal(row.recoveries,0);}});
test('Une nouvelle tentative échouée ne rajeunit pas la donnée',()=>{const a=O.clocks(live,evo,{observed_at:'2026-10-05T20:00:00Z',result:'failure',observation:'FAILED'});assert.equal(a.material_at,live.updated_at);assert.equal(a.market_date,'2026-10-02');assert.equal(a.runner.result,'failure');assert.equal(a.page_check_is_source_recovery,false);});
test('Une panne de source de test conserve le dernier succès',()=>{const l={snapshot_id:'S',updated_at:'2026-01-01T00:00:00Z',sources:[{id:'TEST',health:'UNAVAILABLE',checked_at:'2026-01-03T00:00:00Z',error:'HTTP 503'}]},e={source_snapshot_id:'S',self_model:{health_memory:{history:[{source_snapshot_id:'S',source_checks:[{id:'TEST',state:'LIVE_VERIFIED',checked_at:'2026-01-01T00:00:00Z',executed:true}]}]}}};const row=O.sourceRows(l,e)[0];assert.equal(row.last_success,'2026-01-01T00:00:00Z');assert.equal(row.last_attempt,'2026-01-03T00:00:00Z');assert.equal(row.state,'DEGRADED');assert.equal(row.cause,'HTTP 503');});
test('Observation non exécutée ne prouve pas une récupération',()=>{const e=structuredClone(evo);const issue=e.self_model.health_memory.issues['source:AFT_RSS'];issue.treatment.recovery_observed=0;e.self_model.health_memory.history.push({source_snapshot_id:live.snapshot_id,source_checks:[{id:'AFT_RSS',state:'LIVE_VERIFIED',checked_at:'2026-10-05T20:00:00Z',executed:false}]});assert.equal(O.sourceRows(live,e).find(s=>s.id==='AFT_RSS').last_success,null);});
test('Dernier succès conservé à travers les instantanés de la mémoire liée',()=>{const e=structuredClone(evo);e.self_model.health_memory.history.push({source_snapshot_id:'OLDER',source_checks:[{id:'AFT_RSS',state:'LIVE_VERIFIED',checked_at:'2026-09-01T00:00:00Z',executed:true}]});const row=O.sourceRows(live,e).find(s=>s.id==='AFT_RSS');assert.equal(row.last_success,'2026-09-01T00:00:00Z');assert.equal(row.health,'UNAVAILABLE');assert.equal(row.action_route,'#/objet/LA_BETE_AFT_PUBLIC_DATA_ACCESS_V1');});
test('Évolution de mauvais snapshot ignorée',()=>{const e={...evo,source_snapshot_id:'OTHER'};assert.equal(O.sourceRows(live,e).find(s=>s.id==='AFT_RSS').attempts,null);assert.equal(O.clocks(live,e).presentation_at,null);assert.equal(O.commercial(live,e).state,'UNKNOWN');});
test('Offre fermée issue du modèle existant',()=>{const c=O.commercial(live,evo);assert.equal(c.state,'DESIGN_ONLY_NOT_FOR_SALE');assert.match(c.label,/non ouvert à la vente/);assert.doesNotMatch(c.label,/€|2 500|290/);});
test('Aucune mutation du canon ou de la mémoire',()=>assert.equal(JSON.stringify({live,evo}),before));
console.log(JSON.stringify({schema:'LA_BETE_LOT1_UNIT_RECEIPT',passed:n,results},null,2));
