#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const {spawn}=require('node:child_process'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'../docs');
const OUT=process.env.LA_BETE_ADVISORY_PROOF_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'la-bete-advisory-house-v5-'));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'};
let server,chrome,socket;
async function main(){
 server=http.createServer((req,res)=>{const file=path.resolve(ROOT,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(ROOT+'/')){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(fs.readFileSync(file));}catch(_){res.writeHead(404);res.end('not found');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const profile=fs.mkdtempSync(path.join(OUT,'profile-')),exe=process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
 chrome=spawn(exe,['--headless=new','--no-first-run','--no-default-browser-check','--disable-background-networking','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
 let logs='';chrome.stderr.on('data',d=>logs=(logs+d).slice(-5000));
 for(let i=0;i<80&&!fs.existsSync(path.join(profile,'DevToolsActivePort'));i++)await sleep(100);
 if(!fs.existsSync(path.join(profile,'DevToolsActivePort')))throw Error('CHROME_START_FAILED '+logs);
 const port=Number(fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0]);
 const target=await(await fetch('http://127.0.0.1:'+port+'/json/new?about:blank',{method:'PUT'})).json();
 socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});
 let seq=0;const pending=new Map(),exceptions=[];
 socket.onmessage=e=>{const x=JSON.parse(e.data);if(x.id){const cb=pending.get(x.id);if(cb){pending.delete(x.id);x.error?cb.reject(Error(JSON.stringify(x.error))):cb.resolve(x.result);}}else if(x.method==='Runtime.exceptionThrown')exceptions.push(x.params.exceptionDetails.exception?.description||x.params.exceptionDetails.text);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
 const evaljs=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value;};
 const wait=async(expr,why)=>{for(let i=0;i<100;i++){if(await evaljs(expr))return;await sleep(80);}throw Error('WAIT '+why);};
 const shot=async name=>{const r=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(OUT,name+'.png'),Buffer.from(r.data,'base64'));};
 const pass=x=>console.log('PASS '+x);
 await send('Page.enable');await send('Runtime.enable');await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:960,deviceScaleFactor:1,mobile:false});
 const url='http://127.0.0.1:'+server.address().port+'/france-debt-rate-risk-live-2026-10-02.html';
 await send('Page.navigate',{url});await wait("document.readyState==='complete'&&!!window.LaBeteAdvisoryHouseV5",'house boot');
 assert.equal(await evaljs("document.querySelectorAll('#advisory-house-v5').length"),1);
 assert.equal(await evaljs("document.querySelectorAll('.houseRoomButton').length"),5);
 assert.equal(await evaljs("document.querySelectorAll('.housePane:not([hidden])').length"),1);
 assert.equal(await evaljs("window.LaBeteAdvisoryHouseV5.state().room"),'desk');pass('one desk opens as the single active spatial surface');
 assert.equal(await evaljs("document.getElementById('housePrivateDoor').getAttribute('href')"),'supra://private-office');pass('public House exposes one payload-free handoff to the SUPRA private office');
 assert.deepEqual(await evaljs("({engine:LaBeteAdvisoryHouseV5.second_engine,registry:LaBeteAdvisoryHouseV5.second_registry,truth:LaBeteAdvisoryHouseV5.second_truth,privateStorage:LaBeteAdvisoryHouseV5.private_storage})"),{engine:false,registry:false,truth:false,privateStorage:false});pass('no second engine registry truth or public private-storage');
 for(const id of ['dialogue-public','decision-twin','evidence-graph','experience-explore','supra-mission'])assert.equal(await evaljs("document.querySelectorAll('#"+id+"').length"),1);
 pass('existing canonical surfaces are moved, never cloned');
 const desktop=await evaljs("(()=>{const h=document.getElementById('advisory-house-v5').getBoundingClientRect();return {left:h.left,right:h.right,width:h.width,vw:innerWidth,top:h.top}})()");
 assert.ok(desktop.left>=0&&desktop.right<=desktop.vw+1&&desktop.width>900);pass('desktop house fits viewport');
 await evaljs("document.querySelector('[data-house-room=decision]').click()");await wait("LaBeteAdvisoryHouseV5.state().room==='decision'",'decision');
 assert.equal(await evaljs("document.querySelectorAll('.housePane:not([hidden]) #decision-twin').length"),1);
 assert.ok((await evaljs("document.getElementById('houseCommittee').textContent")).includes('NONE_EVIDENCED'));
 assert.ok((await evaljs("document.getElementById('houseCommitteeConsensus').textContent")).includes('Ne pas décider'));
 pass('Decision Twin is the only active decision room and Committee is a summary, not agent theatre');
 await evaljs("document.querySelector('[data-house-room=proof]').click()");await wait("LaBeteAdvisoryHouseV5.state().room==='proof'",'proof');
 assert.equal(await evaljs("document.querySelectorAll('.housePane:not([hidden]) #evidence-graph').length"),1);pass('ProofGraph remains the same proof room');
 await evaljs("document.querySelector('[data-house-room=explore]').click()");await wait("LaBeteAdvisoryHouseV5.state().room==='explore'",'explore');
 assert.equal(await evaljs("document.getElementById('experience-explore').open"),true);
 assert.equal(await evaljs("document.body.classList.contains('mu-active')"),false);pass('Cosmos is visible as an option but not activated by entering Explore');
 await evaljs("document.querySelector('[data-house-room=desk]').click();document.getElementById('beastDialogueInput').value='Je veux acheter une entreprise en Espagne';document.getElementById('beastDialogueInput').dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('beastDialogueForm').requestSubmit()");
 await wait("LaBeteAdvisoryHouseV5.state().room==='mission'",'auto route mission');
 assert.ok((await evaljs("document.getElementById('houseRouteHint').textContent")).includes('M&A + Financement + Evidence'));
 assert.ok((await evaljs("document.getElementById('houseRouteHint').textContent")).includes('Binding SUPRA prouvé'));
 assert.ok((await evaljs("document.getElementById('houseMissionCapability').textContent")).startsWith('BOUND_EXISTING_SUPRA_COCKPITS_ROUTING_ONLY'));
 assert.ok((await evaljs("document.getElementById('houseMissionCapability').textContent")).includes('Opportunités + Finance + Juridique + Réseau'));
 assert.equal(await evaljs("LaBeteAdvisoryHouseV5.specialist_binding_proof.verdict"),'PROVEN_FOR_V5_BINDING_GATE');
 assert.equal(await evaljs("LaBeteAdvisoryHouseV5.specialist_binding_proof.authority"),'ROUTING_ONLY_NOT_EXECUTION_PROOF');
 assert.ok((await evaljs("document.getElementById('houseMissionNeed').textContent")).includes('entreprise en Espagne'));
 assert.ok((await evaljs("document.getElementById('houseMissionOffer').textContent")).includes('2 500 €'));
 pass('auto-orientation composes a contextual Mission brief from proven existing SUPRA cockpit bindings without execution authority');
 assert.equal(await evaljs("document.querySelectorAll('#reality-pulse').length"),1);
 assert.ok((await evaljs("document.getElementById('realityHeadline').textContent")).length>10);pass('existing Reality Pulse survives inside voluntary exploration');
 await shot('desktop-mission');
 await evaljs("LaBeteAdvisoryHouseV5.setRoom('desk')");await wait("LaBeteAdvisoryHouseV5.state().room==='desk'",'desk restore');await shot('desktop-desk');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});
 await send('Page.reload',{ignoreCache:true});await wait("document.readyState==='complete'&&!!window.LaBeteAdvisoryHouseV5",'mobile boot');
 const mobile=await evaljs("(()=>{const h=document.getElementById('advisory-house-v5').getBoundingClientRect();return {left:h.left,right:h.right,width:h.width,vw:innerWidth,body:document.documentElement.scrollWidth,buttons:document.querySelectorAll('.houseRoomButton').length,visible:document.querySelectorAll('.housePane:not([hidden])').length}})()");
 assert.ok(mobile.left>=-1&&mobile.right<=mobile.vw+1&&mobile.body<=mobile.vw+2);assert.equal(mobile.buttons,5);assert.equal(mobile.visible,1);pass('mobile keeps one room and no horizontal page overflow');
 await shot('mobile-desk');
 assert.equal(exceptions.length,0,'browser exceptions: '+exceptions.join('\n'));
 const receipt={schema:'LA_BETE_ADVISORY_HOUSE_V5_BROWSER_PROOF',desktop,mobile,exceptions,output:OUT,verdict:'PASS'};
 fs.writeFileSync(path.join(OUT,'receipt.json'),JSON.stringify(receipt,null,2));console.log('ADVISORY_HOUSE_V5_BROWSER_PASS '+OUT);
}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;}).finally(async()=>{try{socket?.close();}catch{}try{chrome?.kill('SIGTERM');}catch{}try{server?.close();}catch{}});
