'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const M=require('../docs/assets/la-bete-explorer-model.js');
const live=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-live.json','utf8'));
const evolution=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-evolution.json','utf8'));
// Unit fixture uses the actual pure generator; the live UI is checked separately after publication.
const prepared=JSON.parse(require('node:child_process').execFileSync('python3',['-c',"import sys,json; sys.path.insert(0,'scripts'); from la_bete_acquisition import build_initiatives; print(json.dumps(build_initiatives(json.load(open('docs/data/france-debt-rate-live.json')))))"],{encoding:'utf8'}));
evolution.self_model.acquisition={...evolution.self_model.acquisition,initiatives:prepared};
const territories=JSON.parse(fs.readFileSync('docs/data/france-organism.json','utf8'));
const topo=JSON.parse(fs.readFileSync('docs/data/france-topology.json','utf8'));
const g=M.build(live,evolution,territories,topo),d=topo.detail;let n=0;
function test(label,fn){fn();n++;console.log('PASS '+label);}
test('country and region identities preserved',()=>{assert.ok(g.nodes.has(M.COUNTRY));assert.ok(g.nodes.has('OJO_FRANCE_ORGANISM_V1#/topology/regions/32'));});
test('all departments selectable',()=>assert.equal([...g.nodes.values()].filter(x=>x.kind==='DEPARTMENT').length,d.counts.departments));
test('all API intercommunalities selectable with scoped count',()=>assert.equal([...g.nodes.values()].filter(x=>x.kind==='EPCI').length,d.counts.epcis_catalog));
test('commune index complete but not all detailed objects materialized',()=>{assert.equal(M.communeIndex(d).size,d.counts.communes_cog);assert.ok(g.nodes.size<5000);});
test('regional relations expose departments',()=>assert.ok(M.neighbors(g,'OJO_FRANCE_ORGANISM_V1#/topology/regions/32').some(x=>x.node.id===M.TOPO+'#/departments/60')));
test('department exposes communal index without shard load',()=>assert.ok(M.neighbors(g,M.TOPO+'#/departments/60').some(x=>x.node.id===M.TOPO+'#/communes/60463')));
test('commune index resolves without making up details',()=>{const x=M.resolveNode(g,M.TOPO+'#/communes/60463');assert.equal(x.status,'INDEX_ONLY');assert.equal(x.data.population,undefined);});
test('communal search uses real index',()=>{const result=M.search(g,'Nogent-sur-Oise');assert.ok(result.some(x=>x.id===M.TOPO+'#/communes/60463'));});
test('unknown commune fails closed',()=>assert.equal(M.resolveNode(g,M.TOPO+'#/communes/99999'),null));
const descriptor=d.shards['60'],raw=fs.readFileSync('docs/'+descriptor.path),shard=JSON.parse(raw);
test('department shard exact content hash',()=>assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),descriptor.sha256));
const full=M.build(live,evolution,territories,topo,new Map([['60',shard]]));
test('full commune loads actual source values',()=>{const x=M.resolveNode(full,M.TOPO+'#/communes/60463');assert.equal(x.data.population,shard.communes.find(c=>c.code==='60463').population);assert.equal(x.data.local_debt_effect,'NOT_DOCUMENTED');});
test('commune links to correct intercommunality',()=>assert.ok(M.neighbors(full,M.TOPO+'#/communes/60463').some(x=>x.node.id===M.TOPO+'#/epcis/200068047')));
test('population epoch not fabricated',()=>assert.ok(M.facts(M.resolveNode(full,M.TOPO+'#/communes/60463'),full).some(([k,v])=>k==='Millésime de population'&&v.includes('NON FOURNI'))));
test('all historical observations exposed',()=>assert.equal([...g.nodes.values()].filter(x=>x.kind==='HISTORICAL_OBSERVATION').length,live.curve_history.length));
test('financial object values reference existing feed',()=>{for(const x of g.nodes.values())if(x.kind==='FINANCIAL_METRIC')assert.equal(x.data.value,live.observed[x.data.key]);});
test('all four documented horizons',()=>assert.equal([...g.nodes.values()].filter(x=>x.kind==='HORIZON').length,live.refinancing_twin.views.length));
test('unknown financing need not filled',()=>{const x=[...g.nodes.values()].find(x=>x.kind==='HORIZON'&&x.data.financing_need_bne===null);assert.ok(M.facts(x,g).some(([k,v])=>v==='UNKNOWN'));});
test('scenario shapes remain conditional',()=>assert.ok([...g.nodes.values()].filter(x=>x.kind==='SCENARIO_DETAIL').every(x=>x.status==='STRESS_NOT_FORECAST')));
test('health dimensions not national scores',()=>{const xs=[...g.nodes.values()].filter(x=>x.kind==='HEALTH_DIMENSION');assert.ok(xs.length>0);assert.ok(xs.every(x=>M.facts(x,g).some(([k,v])=>v.includes('pas un diagnostic'))));});
test('municipal and editorial proposals are not executions',()=>{const xs=[...g.nodes.values()].filter(x=>['INITIATIVE','EDITORIAL_PROPOSAL'].includes(x.kind));assert.equal(xs.length,3);assert.ok(xs.every(x=>x.data.external_action==='NOT_EXECUTED'&&x.data.automatic_publication===false));});
test('recorded official directory contact only',()=>{const x=g.nodes.get('LA_BETE_MUNICIPAL_DIALOGUE_60463_V1');assert.ok(x.data.contact.source_url.startsWith('https://lannuaire.service-public.gouv.fr/'));assert.equal(x.data.contact.recheck_before_send,true);});
test('no synthetic audio or video completion',()=>{for(const x of g.nodes.values())if(x.kind==='EDITORIAL_PROPOSAL'){assert.equal(x.data.production.release,'Non publié');assert.ok(!x.data.production.audio_file&&!x.data.production.video_file);}});
test('index is a descriptor not an alternate financial truth',()=>assert.ok(!JSON.stringify(d).includes('tec10_pct')));
test('nonexistent territorial details never invented',()=>{const empty=M.build(live,evolution,territories);assert.equal(M.resolveNode(empty,M.TOPO+'#/communes/60463'),null);});
const ui=fs.readFileSync('docs/assets/la-bete-explorer.js','utf8');
test('UI population is paginated',()=>{assert.match(ui,/const pageSize=40/);assert.match(ui,/Afficher davantage/);});
test('commune shard must pass digest gate',()=>assert.match(ui,/expectedSHA256:descriptor.sha256/));
test('no mail or social publishing adapter activated',()=>assert.doesNotMatch(ui,/smtp|mailto:|youtube.*upload|spotify.*publish|Authorization:/i));
console.log('LA_BETE_ENRICHMENT_TESTS_PASS '+n);
