#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const {spawn}=require('node:child_process'),assert=require('node:assert/strict');
const ROOT=path.resolve(__dirname,'../docs');
const OUT=process.env.LA_BETE_HOUSE_GAME_MOBILE_PROOF_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'la-bete-house-game-mobile-'));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.usdz':'model/vnd.usdz+zip'};
let server,chrome,socket;
async function main(){
  server=http.createServer((req,res)=>{const file=path.resolve(ROOT,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(ROOT+'/')){res.writeHead(403);return res.end();}try{res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(fs.readFileSync(file));}catch(_){res.writeHead(404);res.end('not found');}});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));fs.mkdirSync(OUT,{recursive:true});
  const profile=fs.mkdtempSync(path.join(OUT,'profile-')),exe=process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  chrome=spawn(exe,['--headless=new','--no-first-run','--no-default-browser-check','--disable-background-networking','--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader','--use-angle=swiftshader','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:['ignore','ignore','pipe']});
  let logs='';chrome.stderr.on('data',d=>logs=(logs+d).slice(-5000));
  for(let i=0;i<80&&!fs.existsSync(path.join(profile,'DevToolsActivePort'));i++)await sleep(100);
  if(!fs.existsSync(path.join(profile,'DevToolsActivePort')))throw Error('CHROME_START_FAILED '+logs);
  const port=Number(fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0]);
  const target=await(await fetch('http://127.0.0.1:'+port+'/json/new?about:blank',{method:'PUT'})).json();
  socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});
  let seq=0;const pending=new Map(),exceptions=[];
  socket.onmessage=e=>{const x=JSON.parse(e.data);if(x.id){const cb=pending.get(x.id);if(cb){pending.delete(x.id);x.error?cb.reject(Error(JSON.stringify(x.error))):cb.resolve(x.result);}}else if(x.method==='Runtime.exceptionThrown')exceptions.push(x.params.exceptionDetails.exception?.description||x.params.exceptionDetails.text);};
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaljs=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result?.value;};
  const wait=async(expr,why)=>{for(let i=0;i<360;i++){if(await evaljs(expr))return;await sleep(100);}throw Error('WAIT '+why);};
  const shot=async name=>{const r=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(OUT,name+'.png'),Buffer.from(r.data,'base64'));};
  await send('Page.enable');await send('Runtime.enable');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});
  const url='http://127.0.0.1:'+server.address().port+'/france-debt-rate-risk-live-2026-10-02.html';
  await send('Page.navigate',{url});await wait("document.readyState==='complete'&&!!window.LaBeteHouseGameV1",'mobile script');
  await evaljs("LaBeteHouseGameV1.enter({pointerLock:false})");
  await wait("LaBeteHouseGameV1.state().active&&LaBeteHouseGameV1.state().avatar_model_mode==='canonical_glb_skinned_curved_face_v2_web_preview'",'mobile first-slice rigged game');
  const mobile=await evaljs("(()=>{const c=document.querySelector('#beastMount canvas')?.getBoundingClientRect(),touch=getComputedStyle(document.querySelector('.houseGameTouch')),e=document.getElementById('houseGameInteractMobile').getBoundingClientRect();return {vw:innerWidth,body:document.documentElement.scrollWidth,canvas:c&&{left:c.left,right:c.right,width:c.width,height:c.height},touch:touch.display,dpad:document.querySelectorAll('.houseGameDpad button').length,interact:{w:e.width,h:e.height},state:LaBeteHouseGameV1.state()}})()");
  assert.ok(mobile.body<=mobile.vw+2,JSON.stringify(mobile));
  assert.equal(mobile.touch,'flex');assert.equal(mobile.dpad,4);assert.ok(mobile.interact.w>=44&&mobile.interact.h>=44);
  assert.equal(mobile.state.native_skeleton_loaded,true);assert.equal(mobile.state.first_slice_only,true);assert.equal(mobile.state.avatars.length,2);assert.equal(mobile.state.physical_doors,2);
  console.log('PASS mobile 3D uses one rigged House with touch controls and no horizontal overflow');
  const z0=await evaljs("LaBeteHouseGameV1.state().player.z");
  assert.equal(await evaljs("LaBeteHouseGameV1.control('forward',true)"),true);
  await evaljs("(()=>{const base=performance.now();for(let i=1;i<=18;i++)window.LaBeteThreeFrameHook(base+i*50,window.LaBeteThreeRuntime);return true})()");
  assert.equal(await evaljs("LaBeteHouseGameV1.control('forward',false)"),true);
  const z1=await evaljs("LaBeteHouseGameV1.state().player.z");assert.ok(z1<z0-.4,JSON.stringify({z0,z1}));
  console.log('PASS mobile D-pad control path moves through the same locomotion API');
  assert.equal(await evaljs("LaBeteHouseGameV1.interact()"),true);await wait("document.getElementById('houseGamePanel').hidden===false",'mobile desk interaction');
  const panel=await evaljs("(()=>{const r=document.getElementById('houseGamePanel').getBoundingClientRect();return {left:r.left,right:r.right,width:r.width,vw:innerWidth,title:document.getElementById('houseGamePanelTitle').textContent,intro:document.getElementById('houseGamePanelIntro').textContent}})()");
  assert.ok(panel.left>=0&&panel.right<=panel.vw+1&&panel.title.length>5,JSON.stringify(panel));
  assert.match(panel.intro,/Decision/);
  console.log('PASS mobile E interaction opens Bureau guidance inside viewport');
  await shot('mobile-house-game-desk');
  assert.equal(exceptions.length,0,'browser exceptions: '+exceptions.join('\n'));
  const receipt={schema:'LA_BETE_HOUSE_GAME_V1_MOBILE_BROWSER_PROOF',mobile,panel,exceptions,verdict:'PASS',output:OUT};fs.writeFileSync(path.join(OUT,'receipt.json'),JSON.stringify(receipt,null,2));
  console.log('LA_BETE_HOUSE_GAME_V1_MOBILE_BROWSER_PASS '+OUT);
}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;}).finally(()=>{try{socket?.close();}catch{}try{chrome?.kill('SIGTERM');}catch{}try{server?.close();}catch{}});
