'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const M=require('../docs/assets/la-bete-explorer-model.js'),D=require('../docs/assets/la-bete-dialogue.js');
const live=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-live.json','utf8'));
const evolution=JSON.parse(fs.readFileSync('docs/data/france-debt-rate-evolution.json','utf8'));
const territories=JSON.parse(fs.readFileSync('docs/data/france-organism.json','utf8'));
const evidence=JSON.parse(fs.readFileSync('docs/data/la-bete-evidence-universe-v1.json','utf8'));
const before=JSON.stringify({live,evolution,territories}),g=M.build(live,evolution,territories),cosmos=M.spatialProjection(g,evidence);
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
test('canonical country identity reused',()=>assert.equal(g.nodes.get(M.COUNTRY).id,live.france_binding.country_object_id));
test('canonical finance identity reused',()=>assert.equal(g.nodes.get(M.FINANCE).id,live.france_binding.system_id));
test('single debt object references original payload',()=>assert.strictEqual(g.nodes.get(M.DEBT).data,live));
test('source payload not duplicated',()=>assert.strictEqual(g.nodes.get(live.sources[0].id).data,live.sources[0]));
test('unique node identity',()=>assert.equal(new Set([...g.nodes.keys()]).size,g.nodes.size));
test('unique relation identity',()=>assert.equal(new Set(g.edges.map(e=>[e.from,e.to,e.relation].join('|'))).size,g.edges.length));
test('cosmos is a derived projection over the one evidence registry',()=>{assert.equal(cosmos.schema,'LA_BETE_COSMOS_SPATIAL_PROJECTION_V1');assert.equal(cosmos.state,'DERIVED_VIEW_ONLY');assert.equal(cosmos.planets.length,evidence.coverage.objects_total);assert.equal(new Set(cosmos.planets.map(x=>x.object_id)).size,cosmos.planets.length);assert.ok(cosmos.planets.every(x=>x.object===evidence.objects[x.object_id]));assert.equal(cosmos.contract.second_registry,false);assert.equal(cosmos.contract.second_runtime,false);assert.equal(cosmos.contract.persistent_spatial_registry,false);});
test('cosmos projects galaxies systems moons and ProofGraph wormholes',()=>{assert.equal(cosmos.galaxies.length,4);assert.ok(cosmos.systems.length>=10);assert.ok(cosmos.moons.length>cosmos.planets.length);assert.ok(cosmos.wormholes.length>0);assert.equal(cosmos.source_projection_fingerprint,evidence.projection_fingerprint);});
test('canonical spatial traversal crosses a proof wormhole into another object',()=>{const t=cosmos.traversal;assert.ok(t);assert.notEqual(t.planet_id,t.target_object_id);assert.ok(cosmos.planetById.has(t.planet_id));assert.ok(cosmos.planetById.has(t.target_object_id));const moon=cosmos.moons.find(x=>x.id===t.moon_id),wormhole=cosmos.wormholes.find(x=>x.id===t.wormhole_id);assert.ok(moon);assert.ok(wormhole);assert.equal(moon.planet_id,t.planet_id);assert.equal(moon.proof_ref,t.proof_ref);assert.equal(wormhole.from_object_id,t.planet_id);assert.equal(wormhole.to_object_id,t.target_object_id);assert.equal(wormhole.relation,'PROOF_REF');});
test('all relations resolve',()=>assert.ok(g.edges.every(e=>g.nodes.has(e.from)&&g.nodes.has(e.to))));
test('every canonical ProofGraph edge preserved',()=>assert.ok(live.evidence_graph.edges.every(e=>g.edges.some(x=>x.from===e.from&&x.to===e.to&&x.relation===e.relation))));
test('country to finance to debt traversal',()=>{assert.ok(M.neighbors(g,M.COUNTRY).some(x=>x.node.id===M.FINANCE));assert.ok(M.neighbors(g,M.FINANCE).some(x=>x.node.id===M.DEBT));});
test('source reaches official organization group',()=>assert.ok(M.neighbors(g,'AFT_RSS').some(x=>x.node.id==='source-domain:www.aft.gouv.fr')));
test('claim reaches proof source',()=>assert.ok(M.neighbors(g,'TEC10').some(x=>x.node.id==='BDF_TEC')));
test('territories not fetched or fabricated by model',()=>assert.equal([...M.build(live,evolution).nodes.values()].filter(x=>x.kind==='REGION').length,0));
test('regional records match existing document',()=>assert.equal([...g.nodes.values()].filter(x=>x.kind==='REGION').length,territories.topology.regions.length));
test('no region-specific national rate',()=>{const n=[...g.nodes.values()].find(x=>x.kind==='REGION');const f=M.facts(n,g);assert.ok(f.some(x=>x[1].includes('NON DOCUMENTÉ')));assert.ok(!f.some(x=>x[0]==='TEC10'));});
test('department drilldown not fabricated',()=>assert.ok(![...g.nodes.values()].some(x=>x.kind==='DEPARTMENT')));
test('route roundtrip canonical slash and fragment identity',()=>{const p=M.parseRoute(M.route('objet',M.COUNTRY,live.snapshot_id));assert.equal(p.id,M.COUNTRY);assert.equal(p.snapshot,live.snapshot_id);});
test('known universe route',()=>assert.deepEqual(M.parseRoute('#/univers/demarches'),{kind:'univers',id:'demarches',snapshot:null}));
for(const kind of ['public','agir','scic','services','prive'])test('hybrid product route '+kind,()=>assert.deepEqual(M.parseRoute('#/'+kind),{kind,snapshot:null}));
test('unknown universe is not promoted',()=>assert.equal(M.parseRoute('#/univers/secret').kind,'invalid'));
test('malformed escape rejected',()=>assert.equal(M.parseRoute('#/objet/%GG').kind,'invalid'));
test('overlong object rejected',()=>assert.equal(M.parseRoute('#/objet/'+'a'.repeat(501)).kind,'invalid'));
test('script snapshot rejected',()=>assert.equal(M.parseRoute('#/atlas?snapshot=javascript:alert(1)').kind,'invalid'));
test('URL javascript blocked',()=>assert.equal(M.safeURL('javascript:alert(1)'),null));
test('URL private host blocked',()=>assert.equal(M.safeURL('https://127.0.0.1/secret'),null));
test('URL credentials blocked',()=>assert.equal(M.safeURL('https://person:secret@www.aft.gouv.fr/fr'),null));
test('official publication URL allowed',()=>assert.ok(M.safeURL('https://www.assemblee-nationale.fr/dyn/test.pdf')));
test('accent-insensitive search',()=>assert.ok(M.search(g,'tresor').some(n=>n.label==='Agence France Trésor')));
test('stable search order no generated scoring',()=>assert.deepEqual(M.search(g,'source').map(x=>x.id),M.search(g,'source').map(x=>x.id)));
test('unknown search has no invented objects',()=>assert.equal(M.search(g,'unicorn-not-present-9999').length,0));
test('mismatched evolution cannot supply requests',()=>{const wrong={...evolution,source_snapshot_id:'OJO-DIFFERENT'};assert.equal([...M.build(live,wrong).nodes.values()].filter(x=>x.kind==='REQUEST').length,0);});
test('unverified evolution cannot supply requests',()=>{const wrong={...evolution,status:'CANDIDATE'};assert.equal([...M.build(live,wrong).nodes.values()].filter(x=>x.kind==='REQUEST').length,0);});
for(const n of [...g.nodes.values()].filter(n=>n.kind==='REQUEST'))test('draft request has real source gap paths '+n.id,()=>{assert.ok(M.neighbors(g,n.id).length);assert.ok(M.neighbors(g,n.id).every(x=>x.node.kind==='GAP'));assert.equal(n.data.external_action,'NOT_EXECUTED');});
test('object dialogue uses exact object and snapshot',()=>{const n=g.nodes.get('AFT_RSS');const c=M.dialogueContext(n,g);const r=D.analyze('Pourquoi cet accès manque ?', {live,evolution,object:c});assert.equal(r.status,'OBJECT_CONTEXT');assert.ok(r.summary.includes(n.label));assert.ok(r.retained.some(x=>x.includes(n.data.health)));});
test('regional dialogue cannot return national rate as local',()=>{const n=[...g.nodes.values()].find(x=>x.kind==='REGION');const r=D.analyze('Quel taux dans cette région ?', {live,evolution,object:M.dialogueContext(n,g)});assert.equal(r.status,'OBJECT_CONTEXT');assert.ok(r.limits.some(x=>x.includes('Aucun effet local')));});
test('political input remains factual with object context',()=>{const r=D.analyze('Quel candidat devrait gagner ?', {live,evolution,object:M.dialogueContext(g.nodes.get(M.DEBT),g)});assert.equal(r.status,'FACTUAL_REVIEW_ONLY');assert.equal(r.political_recommendation,'NONE');});
test('context does not authorize sending',()=>{const r=D.analyze('Envoie un mail maintenant', {live,evolution,object:M.dialogueContext(g.nodes.get('AFT_RSS'),g)});assert.equal(r.external_action,'NONE');});
test('canonical values and files unchanged',()=>assert.equal(JSON.stringify({live,evolution,territories}),before));
const ui=fs.readFileSync('docs/assets/la-bete-explorer.js','utf8'),model=fs.readFileSync('docs/assets/la-bete-explorer-model.js','utf8'),page=fs.readFileSync('docs/france-debt-rate-risk-live-2026-10-02.html','utf8'),explorerCss=fs.readFileSync('docs/assets/la-bete-explorer.css','utf8'),artCss=fs.readFileSync('docs/assets/la-bete-art.css','utf8');
test('no second polling loop',()=>assert.doesNotMatch(ui+'\n'+model,/setInterval\s*\(|setTimeout\s*\(|requestAnimationFrame\s*\(/));
test('civic institutional palette is explicit and neutral',()=>{
 const tail=explorerCss.slice(explorerCss.lastIndexOf('CIVIC INSTITUTIONAL PALETTE V1'));
 assert.match(tail,/--civic-blue:#5B7C99/);
 assert.match(tail,/--civic-sage:#6F8F86/);
 assert.match(tail,/--civic-copper:#B58A62/);
 assert.match(tail,/--civic-alert:#B55E63/);
 assert.doesNotMatch(tail,/var\(--supra-red/);
 assert.match(artCss.slice(artCss.lastIndexOf('CIVIC INSTITUTIONAL PALETTE V1')),/--art-copper:#B58A62/);
});
test('public cache keys expose current civic art and official territory discovery',()=>{
 assert.match(page,/la-bete-art\.css\?v=20261004-civic-institutional-v1/);
 assert.match(page,/la-bete-explorer\.css\?v=20261004-cosmos-spatial-v1/);
 assert.match(page,/la-bete-explorer-model\.js\?v=20261004-cosmos-spatial-v1/);
 assert.match(page,/la-bete-explorer\.js\?v=20261004-cosmos-spatial-v1/);
});
test('no hidden dialog transcript persistence',()=>assert.doesNotMatch(ui,/localStorage|sessionStorage|indexedDB|document\.cookie/));
test('no public action API or credentials',()=>assert.doesNotMatch(ui,/Bearer |POST["']|OPENAI_API_KEY|GH_TOKEN|18765|localhost/));
test('no user HTML execution sinks',()=>assert.doesNotMatch(ui,/innerHTML|outerHTML|insertAdjacentHTML|\beval\(|new Function/));
test('territory contribution UI discloses external GitHub account gate',()=>{assert.match(ui,/exige un compte \/ une connexion GitHub/);assert.match(ui,/territory-contribution\.yml/);assert.match(ui,/labels=territoire/);assert.match(ui,/\[CANDIDATE /);});
test('territory discovery is fail closed and separate from canon',()=>{assert.match(ui,/LA_BETE_TERRITORY_DISCOVERY_CANDIDATES_V1/);for(const x of ['automatic_discovery_is_proof','automatic_discovery_can_promote_living_identity','automatic_discovery_mints_phi','automatic_discovery_changes_documentation_score'])assert.ok(ui.includes(x));assert.match(ui,/verified_receipt_required_for_phi/);assert.match(ui,/CANDIDATS À VÉRIFIER · NON CANON/);assert.match(ui,/la-bete-territory-discovery-candidates-v1\.json/);});
test('confidence universe is distinct from canonical proofs',()=>{assert.ok(M.UNIVERSES.some(x=>x.id==='preuves'));assert.ok(M.UNIVERSES.some(x=>x.id==='confiance'));assert.notEqual(M.UNIVERSES.find(x=>x.id==='preuves').id,M.UNIVERSES.find(x=>x.id==='confiance').id);assert.match(ui,/universe==='confiance'/);});
test('evidence universe is fail closed and derived from ProofGraph',()=>{for(const x of ['LA_BETE_EVIDENCE_UNIVERSE_V1','READ_ONLY_PUBLIC_PROOFGRAPH_DERIVED_PROJECTION','proofgraph_is_spine','truth_verdict','authenticity_verdict','automatic_phi_minting','second_runtime','second_registry','second_scheduler'])assert.ok(ui.includes(x));assert.match(ui,/la-bete-evidence-universe-v1\.json/);});
test('trust smca and uscrc UI never claim truth or certificate',()=>{assert.match(ui,/Indice de préparation documentaire/);assert.match(ui,/jamais un score de vérité/);assert.match(ui,/uSCRC · contexte seulement/);assert.match(ui,/Deep SMCA · exécuté/);assert.doesNotMatch(ui,/uSCRC · CERTIFIÉ/);});
test('evidence universe exposes the expanded object ontology without fabricating empty kinds',()=>{for(const x of ['Univers d’objets couverts','Documents','Personnes','Organisations','Entreprises','Initiatives','Opportunités','Décisions','Vidéos','Audio','Archives','Contributions','Relations','schéma prêt, aucun objet vérifié'])assert.ok(ui.includes(x));});
test('evidence profiles decorate sources claims and territorial media without action authority',()=>{assert.match(ui,/evidenceProfileForNode/);assert.match(ui,/evidenceProfileForCandidate/);assert.match(ui,/evidenceProfileForLivingMedia/);assert.match(ui,/proofBody\.append\(evidenceProfilePanel/);assert.doesNotMatch(ui,/EVIDENCE.*POST|TRUST.*POST|USCRC.*POST/i);});
test('living identity is fail closed and loaded through canonical reader',()=>{assert.match(ui,/LA_BETE_TERRITORY_LIVING_IDENTITY_V1/);assert.match(ui,/no_random_identity_color/);assert.match(ui,/no_unlicensed_image/);assert.match(ui,/empty_is_better_than_fabricated/);assert.match(ui,/la-bete-territory-living-identity-v1\.json/);assert.doesNotMatch(ui,/fetch\([^)]*territory-living/i);});
test('lazy territorial read uses existing bounded fetch',()=>assert.match(ui,/laBeteReadCanonicalJSON\('data\/france-organism\.json'/));
test('native browser navigation and modal semantics',()=>{assert.match(ui,/history\.pushState/);assert.match(ui,/popstate/);assert.match(ui,/showModal\(/);});
test('three is not eagerly initialized at boot',()=>{const tail=page.slice(page.indexOf('// LA_BETE_BOOT_START'));assert.doesNotMatch(tail,/^initBeast\(\);/m);assert.match(tail,/laBeteEnsurePresence/);});
test('existing body remains no-JavaScript fallback',()=>{assert.match(page,/id="canonicalSnapshot"/);assert.match(page,/id="market-anatomy"/);assert.match(page,/id="dialogue-public"/);});
test('Cosmos mounts the single existing beast stage',()=>assert.match(ui,/mountExisting\('beastStage',scene\)/));
test('Cosmos reuses the existing Three scene renderer and one WebXR-compatible frame loop',()=>{assert.match(page,/EvidenceUniverseCosmosProjection/);assert.match(page,/CanonicalEvidencePlanets/);assert.match(page,/ProofGraphWormholes/);assert.match(page,/window\.laBeteSetCosmosProjection=setCosmosProjection/);assert.match(page,/window\.laBeteCosmosFocus=focusCosmos/);assert.equal((page.match(/new THREE\.WebGLRenderer/g)||[]).length,1);assert.equal((page.match(/function frame\(t\)/g)||[]).length,1);assert.equal((page.match(/renderer\.setAnimationLoop\(frame\)/g)||[]).length,1);assert.equal((page.match(/requestAnimationFrame\(frame\)/g)||[]).length,0);assert.doesNotMatch(ui,/new THREE\.|WebGLRenderer/);});
test('Cosmos primary surface exposes canonical traversal controls',()=>{for(const x of ['COSMOS · PROJECTION SPATIALE DU REGISTRE UNIQUE','GALAXIE','SYSTÈME','PLANÈTE','LUNE / PREUVE','WORMHOLE','AUTRE OBJET','laBeteCosmosFocus'])assert.ok(ui.includes(x));});
test('holographic avatar is a derived navigation actor inside the existing Cosmos',()=>{for(const x of ['HolographicNavigatorAvatar','LA_BETE_HOLOGRAPHIC_AVATAR_XR_V1','DERIVED_NAVIGATION_ACTOR','same_scene:avatarGroup.parent===cosmosGroup','second_world:false','second_engine:false','second_registry:false'])assert.ok(page.includes(x));assert.match(page,/cosmosGroup\.add\(avatarGroup\)/);assert.equal((page.match(/new THREE\.Scene/g)||[]).length,1);assert.equal((page.match(/new THREE\.WebGLRenderer/g)||[]).length,1);});
test('avatar locomotion camera possession and node targeting reuse Cosmos state',()=>{for(const x of ['avatarGoto(v,kind,id)','AVATAR_FOLLOW','data-avatar-move','Posséder la caméra','window.laBeteAvatarControl','window.laBeteAvatarState'])assert.ok(page.includes(x));assert.doesNotMatch(page,/AvatarRegistry|AvatarEngine|new Worker\(/);});
test('WebXR is capability gated on the same renderer and scene',()=>{for(const x of ["renderer.xr.enabled=true","renderer.xr.setReferenceSpaceType('local')","navigator.xr?.isSessionSupported","navigator.xr.requestSession","renderer.xr.setSession(session)","renderer.xr.getController"])assert.ok(page.includes(x));assert.equal((page.match(/setAnimationLoop\(frame\)/g)||[]).length,1);});
test('Atlas itself requests presence initialization',()=>assert.match(ui.slice(ui.indexOf('function atlas(g)'),ui.indexOf('function factTable')),/laBeteEnsurePresence/));
test('presence stays one-click accessible from the header',()=>assert.match(ui,/link\('La Bête','#\/presence','muPresenceShortcut'\)/));
test('hybrid product surfaces reuse loaded evolution',()=>{assert.match(ui,/function hybridView\(kind,g\)/);assert.match(ui,/g\.evolution\?\.self_model\?\.hybrid_model/);assert.doesNotMatch(ui,/la-bete-hybrid.*fetch|fetch\([^)]*hybrid/i);});
test('public and commercial boundaries are first class routes',()=>{for(const r of ['#/public','#/agir','#/scic','#/services','#/prive'])assert.ok(ui.includes(r));});
test('scic surface renders institutional constitution without legal adoption',()=>{for(const x of ['5 collèges proposés · 100 % des voix','Institutions proposées','Anti-capture','Chemin vers la SCIC réelle','Ancrages juridiques à relire avant constitution'])assert.ok(ui.includes(x));});
test('scic surface exposes democracy lifecycle truth firewall and non-binding pilot',()=>{for(const x of ['SCIC · DÉMOCRATIE OPÉRABLE','Pare-feu de vérité','Cycle démocratique','Règles de scrutin','Dossier pilote · chaîne complète sans faux vote réel','Registre public des résultats','Déposer une proposition publique'])assert.ok(ui.includes(x));});
test('scic surface exposes private verified membership without PII',()=>{for(const x of ['Sociétariat vérifié · frontière privée','Inscription réelle ouverte','Jamais publics','Jeton privé à usage unique'])assert.ok(ui.includes(x));});
test('scic surface exposes blind issuer ballot separation and metadata limits',()=>{for(const x of ['Credential anonyme · séparation émetteur / urne','Processus séparés prouvés','Conformité RFC 9474 revendiquée','Risque restant','Unlinkability cryptographique transcript → bulletin'])assert.ok(ui.includes(x));});
test('scic surface exposes fail-closed production privacy gate',()=>{for(const x of ['Production Privacy Gate · fail-closed','PRIMITIVE RFC','BINDING RUNTIME','RÉSEAU OHTTP','Pourquoi la production reste fermée','Standards de référence'])assert.ok(ui.includes(x));});
test('scene is moved, never cloned',()=>assert.doesNotMatch(ui,/cloneNode|new.*WebGLRenderer/));
test('Atlas preserves sensor shutdown when leaving detailed presence',()=>assert.ok(ui.includes("if(!['presence','lecture'].includes(p.kind)||current.isSearch)window.laBeteSuspendPresence?.();")));
console.log('LA_BETE_EXPLORER_TESTS_PASS '+count);
